### ISSUE TITLE
シーンごとにソースコードをファイル分け

### ISSUE THREAD

**Issue by koujiroukawahara** [human-osaka-game-2018/kawahara_shooting#16]
プロジェクトファイルと同階層に全てのソースコードが並んでいて見にくい為、どのシーンのソースコードか1目でわかる様にする

**Comment by taishi-matsumura** [comment]
こういう、仕様とかに関係せずプログラマにしか関係無い種類の作業は、
* issueのタイトル : ソースコードをフォルダ分けする旨を書く
* issueのdescription : その作業をする理由や、それをしたら何が嬉しいのかを書く
* pull requestのタイトル : issueのタイトルと同じでok
* pull requestのdescription : 具体的な作業内容を列挙(VisualStudioで何をするとか、実フォルダをどうするとか)

みたいな感じにしましょう。
